scan_topicname: "/scan"
odom_topicname: "/odom"
vel_topicname: "/cmd_vel"
marker_topicname: "/visualization_marker"
queue_size: "1"
min_angle: 0.0
max_angle: 360.0
max_angle_correction: 2.5

speed: 0.4
brake_distance: 0.0

crash_topicname: /imu
max_dec: 3.0

start_position_x: 200
start_position_y: 200
#g/b/y/r 1-10
goal: "y5"


